"""add cv_files table

Revision ID: 2034269a078b
Revises: b6509c1e2756
Create Date: 2026-03-19 20:37:34.588680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2034269a078b'
down_revision: Union[str, None] = 'b6509c1e2756'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False, server_default='application/octet-stream'),
    sa.Column('file_size', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('version', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_cv_files_analysis_id'), 'cv_files', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_cv_files_user_id'), 'cv_files', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_files_user_id'), table_name='cv_files')
    op.drop_index(op.f('ix_cv_files_analysis_id'), table_name='cv_files')
    op.drop_table('cv_files')
    # ### end Alembic commands ###
