"""Add new features db schema

Revision ID: aa597f3c5559
Revises: 2034269a078b
Create Date: 2026-04-14 14:58:05.205823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa597f3c5559'
down_revision: Union[str, None] = '2034269a078b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_cvs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_jd_text', sa.Text(), nullable=True),
    sa.Column('base_profile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_cvs_user_id'), 'generated_cvs', ['user_id'], unique=False)
    op.add_column('analyses', sa.Column('jd_evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('interview_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('salary_negotiation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('cv_files', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'phone_number')
    op.drop_column('cv_files', 'deleted_at')
    op.drop_column('analyses', 'deleted_at')
    op.drop_column('analyses', 'salary_negotiation')
    op.drop_column('analyses', 'interview_questions')
    op.drop_column('analyses', 'jd_evaluation')
    op.drop_index(op.f('ix_generated_cvs_user_id'), table_name='generated_cvs')
    op.drop_table('generated_cvs')
    # ### end Alembic commands ###
